apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: app-flask
    tier: frontend
  name: app-flask-service
spec:
  type: NodePort
  ports:
  - port: 8080
    protocol: TCP
    nodePort: 30001
    targetPort: 5000
  selector:
    app: app-flask
status:
  loadBalancer: {}
